create database flask_departamentos;
use flask_departamentos;

CREATE TABLE DEPARTAMENTOS(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
NOMBRE VARCHAR(50)
);

INSERT INTO DEPARTAMENTOS(ID, NOMBRE) VALUES(1,"TACNA");
INSERT INTO DEPARTAMENTOS(ID, NOMBRE) VALUES(2,"MOQUEGUA");
INSERT INTO DEPARTAMENTOS(ID, NOMBRE) VALUES(3,"PIURA");
insert into departamentos(nombre) values("puerto maldonado");

SELECT * FROM DEPARTAMENTOS;